### ISSUE TITLE
Add support for custom queries

### ISSUE THREAD

**Issue by mczp** [SiriDB/grafana-siridb-http-datasource#2]
Kudos on siridb excellent work there,
I'd like to ask whether it makes sense to support the plugin with the ability to specify custom queries by a text field, which apparently isn't possible now.

For example I wanted to implement a graph where limited by top 5 entries, and found that it's not possible (at least for me) to do it in grafana directly.

**Comment by joente** [comment]
Not sure if this will help you to build your top 5 entries query, but it is possible to use a raw query by toggling to "edit mode". The capital keywords like `__START__` are replaced by Grafana, for example to a start timestamp. The plugin will understand which time factor (for example: `seconds` or `milliseconds`) must be used to convert a timestamp.

![grafana-raw-query](https://user-images.githubusercontent.com/6572730/39185199-ae0179a2-47c6-11e8-87d0-7d1202b02e64.png)

(screenshot is from Grafana v4.6.1)
